### ISSUE TITLE
[v2017.4.0] There is still a fair amount of ads.

### ISSUE THREAD

**Issue by mkultra329** [lethak/digitally_imported_userscript#1]
I just tried it out today so I can't say how many more but I'll look at the script and the chrome script viewer to see if I can make sense of what is going on.

**Comment by lethak** [comment]
I know of many people still using it, including myself, and its definitively working as intended.

In rare cases, tampermonkey or greasemonkey will inject the script too late or too early causing it to not work or causing some weirdness; reloading the page will suffice to fix the problem ;)


I don't know of any case where you have MORE ads. If that is your case, can you please provide more details like your OS + Browser version as well as your userscript extension and version, and the DI channel you were listening to, and if you were a loggued in with a "free listener account" or not. (no point in using the script if you are Premium)

Thanks

**Comment by lethak** [comment]
please feel free to provide more details when you can
