### ISSUE TITLE
Getting 'Are you still there?' dialog after early Jan 2019 updates

### ISSUE THREAD

**Issue by ScottRFrost** [lethak/digitally_imported_userscript#20]
I think they must have put out some updates, I'm getting the 'Are you still there?' dialog from time to time again.

https://www DOT di DOT fm/channels?filterKey=favorites

**Comment by lethak** [comment]
Hi, are you sure you were running the script properly ?

I looked at the code and it seems nothing has changed much on this, and is still working in the same way as before.

I'll try to keep an eye on it for a few days

**Comment by ScottRFrost** [comment]
Yeah, it was working fine for months.  Not sure what the deal is now.  It's hit or miss.

Firefox Dev Edition 65.0b12 (64-bit)
TamperMonkey 4.8.5847
Script version 2018.7.5

**Comment by lethak** [comment]
Were you connected to your di account ? if yes, with as a Free Listener or Premium ?
Were you using the Private Browsing mode ?
Linux, Mac or Windows ?

So far, it is working as intended from my point of view, please take a screenshot of your browser (url + visible part of page) next time you encounter this.

I suggest trying with Firefox Standard and comparing if any different behavior is manifesting than the Dev Edition you are using. I have too much work to do it at the moment but I will try to help if you can tell me 100% how to replicate.

**Comment by ScottRFrost** [comment]
Uninstalling and reinstalling the script didn't fix it.  Uninstalling and reinstalling TamperMonkey didn't fix it.  I just created a whole new profile for Firefox Dev Ed.  If that doesn't work, I'll try standard.  Thanks for your help!

**Comment by lethak** [comment]
Tested & working as intended:
* TamperMonkey 4.8.5847
* Script version 2018.7.5
* Firefox Quantum 64.0.2 (64-bit)

With TamperMonkey disabled I get the afk popup, and with everything running, no popup.

You didn't answered my previous questions, it may be of some help.

**Comment by ScottRFrost** [comment]
It must have been a conflict with some other addon or setting.  Creating a whole new profile appears to have fixed it.  Thank you for your time.  Keep up the good work!
