### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by artquest** [lethak/digitally_imported_userscript#22]
Thank you for the script! Works perfect!
Is it possible to generate proper playlists with it? Or the presence of the listen key and the ability to download playlists on the player settings page is just a side effect of the script working?

**Comment by lethak** [comment]
Hi

> the ability to download playlists on the player settings page is just a side effect of the script working?

If you are referring to https://www.di.fm/settings and you have not a legitimate premium account, then yes, this is a side effect of the script, without any consequences but if you try to download .pls files, they will contain your listen key attached to your non-premium account and this won't work ultimately.

> Is it possible to generate proper playlists with it?

I assume you use the term "playlist" for the audio channels ? (Vocal trance, Lounge, etc...) if so, I think this is not possible for the previously mentioned reason with the listen key.

They recently introduced a new "playlist" feature https://www.di.fm/playlists but not modifiable.

I think the script could allow users to create their own playlists based on whatever track you want in it, I had that thought for a long time already but the amount of work required to make it is a bit too much for me at the moment.

**Comment by artquest** [comment]
Got it, thank you.

**Comment by lethak** [comment]
I'll keep this issue open a little while to include it in the Troubleshooting documentation later

**Comment by lethak** [comment]
Added to the troubleshooting section of the documentation, now closing
