### ISSUE TITLE
Audio stopping after 30mins when not logged in

### ISSUE THREAD

**Issue by VeoPlays** [lethak/digitally_imported_userscript#23]
See title. Also the popup still appears "Enjoy 30 minutes of music".
Is there a way to perhaps block that too and keep the music from stopping?

**Comment by lethak** [comment]
Hi, some features like those you mentioned are only working with an account.

Just create an account and voila. if like me you cannot stand dropping your email somewhere, you might want to use a quick, disposable email address like http://www.yopmail.com/en/


I'll keep this issue open a little while to include it in the Troubleshooting documentation later

**Comment by lethak** [comment]
Moreover, I'll suggest reloading the page after login since it was never intended for the script to be used while NOT logged in and if the login is done in xhr or fetch, a reload might be necessary for things to run smoothly without any bad side effect.

**Comment by VeoPlays** [comment]
Aah alright, thanks a lot for the explanation!

**Comment by lethak** [comment]
Added to the troubleshooting section of the documentation, now closing

**Comment by lethak** [comment]
Its been a while, but [v2023.3.54](https://github.com/lethak/LTKDIFMU-userscript/releases/tag/v2023.3.54) finally bypassed the registration wall
