### ISSUE TITLE
Auto save

### ISSUE THREAD

**Issue by codex2020** [lethak/digitally_imported_userscript#31]
Hi, 
Thank you for this work. What would it take to have the possibility to automatically save to a folder whenever a new song is played and name the file based on the title ? 

I was thinking something related to trackModel and saving directly the n variable... ?

**Comment by lethak** [comment]
Hi,

I am not going to include this in the script.
However, you can -very easily- build your own script and do it yourself.

I've done an educational gist in the past to explain how to use their event API https://gist.github.com/lethak/e44300e5b85456ea08433c3790009a8b

Have fun !

**Comment by codex2020** [comment]
great work ! thanks!
