### ISSUE TITLE
Provide unminified code

### ISSUE THREAD

**Issue by nmaggioni** [lethak/digitally_imported_userscript#32]
I can imagine why you've minified the code, but this way the script can't easily be inspected before injecting it in the browser.

**Comment by lethak** [comment]
I can imagine why you'd want to inspect the source code, but read the disclaimer carefully and you will learn this script was not provided for you as a granted general public service.

I recently pondered the risks and benefits of making it truly open, and ruled against it for the time being. The number of reasons for doing so is quite large actually and explaining them all in public would defeat some benefits.

I can only give you my words nothing nefarious is going on, and the script's scope is limited by the "[@grant](https://www.tampermonkey.net/documentation.php#_grant)" and "[@include](https://www.tampermonkey.net/documentation.php#_include)" assertions as you can [see here](https://github.com/lethak/LTKDIFMU-userscript/blob/live/DIUserscript.meta.js).

If you are interested in knowing "how it works", I can provide advice, or you can inspect previous revisions prior to packaging and minifying.
