### ISSUE TITLE
ViolentMonkey problem with download

### ISSUE THREAD

**Issue by crzsotona** [lethak/digitally_imported_userscript#36]
Hello,

LTKDIFMU on Violentmonkey cannot download files, it opens as binary blob instead, could you investigate please?

**Comment by lethak** [comment]
Hi,

At first glance and without investigating much it appears [VM do not support](https://violentmonkey.github.io/api/gm/#gm_download) the '[saveAs](https://www.tampermonkey.net/documentation.php#GM_download)' option.

I know of no solution yet unless not using GM_download with VM,

I will look to do this for the next version of the script using GM_info

link & sources:
* https://stackoverflow.com/questions/27487828/how-to-detect-if-a-userscript-is-installed-from-the-chrome-store/27494812#27494812
* https://www.tampermonkey.net/documentation.php#GM_info
* https://violentmonkey.github.io/api/gm/#gm_info

EDIT:

For future research into the subject:
* https://stackoverflow.com/questions/20508788/do-i-need-content-type-application-octet-stream-for-file-download
* https://stackoverflow.com/questions/44235879/force-the-browser-to-download-file-as-csv-from-url
* polyfil https://gist.github.com/ccloli/832a8350b822f3ff5094

# Workaround

Use tempermonkey

**Comment by ReflexivR** [comment]
So tampermonkey works OK downloading still?

**Comment by ReflexivR** [comment]
Just checked and tampermonkey works great downloading still. There's really no benefit to running violentmonkey, right? I would just tell users to switch. Thanks for your script!

**Comment by ReflexivR** [comment]
Downloads do appear to be mp4 rather than mp3 files though. Is this intended?

**Comment by lethak** [comment]
Yeah don't worry about that, it will still work anyway. The actual format is the one you are listening and depends on the audio quality of your free/premium account.

**Comment by lethak** [comment]
On the next release: 

Reverted to old track download method when NOT using Tampermonkey

Those users will be reverted back to the old ways of downloading via [`window.open(url)`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open).
It means those users will not be able to have an automatic normalized file name for the time being, but can still manually download.

Tampermonkey users are not impacted.
