### ISSUE TITLE
After DIFM site update, the Next Track button no longer works.

### ISSUE THREAD

**Issue by ghost** [lethak/digitally_imported_userscript#37]
DIFM did a site update a few minutes ago - saw the "site update" notice pop up. Now, while everything else seems to work ok, the Next Track button cannot be clicked. It also does not have a tooltip (i.e. "Next [DIUserscript]" tooltip doesn't show).

Looking at the DOM, the Previous Track button is an A element with role="button" and the tooltip info. However the Next Track button is a DIV element with role="button" but no other info.

I'm using the current latest version, v2020.6.14.

**Comment by lethak** [comment]
Hi,

Thanks for signaling the problem.

On my end you can still click on the button, its just the mouse cursor still being a standard pointer and not updating to the usual "clickable hand". The underlying "skip" feature still works. Is it the same on your end ?

**Comment by ghost** [comment]
Ok, tried a few things and it seems to just be at my end, sorry. Works fine on Chrome, and on a fresh Firefox profile. So something in my Firefox setup has started interfering with it, but strangely only since the site update - that's why I assumed it was the script. Sorry for the false alarm! >.<
