### ISSUE TITLE
(di) Numeric volume input is broken

### ISSUE THREAD

**Issue by lethak** [lethak/digitally_imported_userscript#46]
Following a platform update,
when enabled, the numeric volume input is broken (CSS only)

Disabling this feature in the userscript's settings will return the volume bar to its normal display

**Comment by cpypcy** [comment]
I have the same problem.

**Comment by antonhoess** [comment]
For me it looks like this (I hope I refer to the same problem):
![image](https://user-images.githubusercontent.com/72655854/103639364-8a398180-4f4e-11eb-9113-76af68980a36.png)

**Comment by ReflexivR** [comment]
> Disabling this feature in the userscript's settings will return the volume bar to its normal display

where is the option to do this in the settings?

**Comment by lethak** [comment]
> where is the option to do this in the settings?

![diuNum1](https://user-images.githubusercontent.com/1705300/104744411-23d21180-574d-11eb-881c-ae0d8b7ea894.PNG)
![diuNum2](https://user-images.githubusercontent.com/1705300/104744414-246aa800-574d-11eb-8e10-e6f9e0f1575c.PNG)

**Comment by ReflexivR** [comment]
Thank you! I did not have this because I was running an old version. Just realized autoupdate in Tampermonkey is not working at all (all my scripts not just yours).

**Comment by lethak** [comment]
This can be turned back on now with latest version v2021.4.43
