### ISSUE TITLE
Auto Stop Music

### ISSUE THREAD

**Issue by opiummmx** [lethak/digitally_imported_userscript#49]
Hi,
Thank you for your great script
Jazz radio now stop music after X minutes, and ask us to click to continue listening.
Could you please add a feature to avoid to click please ? And let the music play as long as the window is open ?
Thnak you very much
Best Regards

**Comment by lethak** [comment]
Bonjour,

En étant connecté avec un compte gratuit ?

Tampermonkey ?
Script version 2020.10.660 ?
Safari ou chrome ?

quel radio channel ?

**Comment by opiummmx** [comment]
Ah oui salut en français le support 👍 

Oui un compte gratuit, mais l'astuce pour lancer les channels payants sans avoir à payer, c'est d'y accéder directement depuis l'url : comme par exemple https://www.jazzradio.com/vibraphonejazz, et non de passer par le top menu présent sur la home.

Voici l'image qu'on voit : 
![jazz](https://user-images.githubusercontent.com/63003901/104014399-3e3b4680-51b3-11eb-8432-c6e90eb76943.PNG)

J'utilise TaperMonkey, chrome Version 87.0.4280.141 (Build officiel) (64 bits), et la V 2020.10.660

En fait j'ai compris ce qu'il se passe : le script ne se lance pas au premier démarrage de chrome. Il le faisait jusqu'à présent. Je pense que le bug vient de chrome, pas de ton script, désolé pour le dérangement.

**Comment by lethak** [comment]
Il y a des soucis d'activation parfois, justement sur les url directes de channel, un problème que je n'arrive pas bien a isoler pour corriger.  Quelques rafraichissement de page et ça passe souvent.
Sinon passer par la home.

Les channels premiums sont supposés être actif même depuis la home, peut importe que ce soir écrit "locked" ou pas, le click doit fonctionner, sauf si ça a changé depuis mon dernier test, encore un sujet a investiguer à l'occasion :D

**Comment by opiummmx** [comment]
Je te remercie pour ton support.

Par contre, je te confirme que le clic depuis **le top menu de la home** ne fonctionne pas, on a cette image de suite : 
![image](https://user-images.githubusercontent.com/63003901/104020063-de499d80-51bc-11eb-8aa6-0b673aeeabb2.png)

Mais via les liens dessous, tu as raison, ça marche !
![image](https://user-images.githubusercontent.com/63003901/104020253-3385af00-51bd-11eb-9c0f-dfc70acac0a2.png)
