### ISSUE TITLE
Download button doesn't appear

### ISSUE THREAD

**Issue by jabernalv** [lethak/digitally_imported_userscript#50]
Suddenly the download button stopped showing.
I have installed the script on Chrome MAC, Brave MAC, Firefox MAC, Chrome Windows, Firefox Windows, without any success.

**Comment by lethak** [comment]
Working as intended on my side

How to reproduce ?

**Comment by jabernalv** [comment]
![PantallaRadioTunes](https://user-images.githubusercontent.com/12943652/106825042-10caa700-6652-11eb-9ceb-840531d0329c.png)
I don't know.
I'm looking through Inspect to see if the button is hidden, but to no avail.

**Comment by jabernalv** [comment]
![PantallaRadioTunes2](https://user-images.githubusercontent.com/12943652/106825228-699a3f80-6652-11eb-9324-a30c241216db.png)

**Comment by jabernalv** [comment]
Other functions are fine, like repeat, or play previous tracks.

**Comment by jabernalv** [comment]
@version 2020.10.660

**Comment by jabernalv** [comment]
I connected through another network, to eliminate possible problems with the local network, I also could not see the button.

**Comment by lethak** [comment]
Still fine here.

Your screenshot shows you are not logged in. The script is not intended to work without an account logged in.

Have you been abusing the download function before ? like using it to auto download stuff without manually interacting with the browser ?

It is possible you may have triggered a security check in the past and have been locked out of downloading.

I'll try to add a warning about this in the future to help prevent it from happening.

**Comment by jabernalv** [comment]
Hi.
I actually have an account, but I didn't put it up for privacy. I'm going to try another account.
thanks for your help

**Comment by jabernalv** [comment]
Yes, with another account it works very well.
Thanks

**Comment by lethak** [comment]
Interesting 🤔 

Also, by reviewing the code I think I found a potential issue with the download button when using a premium account. I will be making a small fix in the next release, make sure to check back after that.

**Comment by jabernalv** [comment]
Yes, my main account is premium.
Thanks

**Comment by Nzzyme** [comment]
@lethak I suppose logging in to the service is required for the download icon to appear and work? Can you please include this point in the Settings page for the Download tile?

https://prnt.sc/10f30my

**Comment by lethak** [comment]
Released version v2021.4.43 should improve/fix this issue.
