### ISSUE TITLE
[Request] Play Track From Beginning

### ISSUE THREAD

**Issue by Nzzyme** [lethak/digitally_imported_userscript#51]
Hi, I would like to suggest a feature. When we click on the play icon of any channel on any service (Radiotunes, DI, etc.), it takes us to that channels page and the audio starts playing. However, it begins playing from the middle or from a point in time in which the stream is live (as it is a live stream). I observed that I was able to click and drag the current playing point all the way to the beginning and start playing the track from the beginning.

Could you therefore implement a feature so that when we click on the play icon, it takes us to the channel page and the audio actually begins playing from the beginning of the track?

**Comment by lethak** [comment]
This will be in the next release, thanks for the idea.

**Comment by lethak** [comment]
Implemented in version v2021.4.43 (enabled by default)

**Comment by Nzzyme** [comment]
Thanks! I tried updating this script in Tampermonkey but it won't update. See screenshot. Can you please advise?

https://prnt.sc/117wp3o

Edit: I closed the browser, launched it again and disabled other scripts except yours and tried again and it worked. Not sure why it didn't work earlier. Anyway, I'll check out the new update and give feedback. Thanks
