### ISSUE TITLE
[Suggestion] Dark Theme

### ISSUE THREAD

**Issue by Nzzyme** [lethak/digitally_imported_userscript#53]
Hello @lethak 

I was wondering if you are able to add a dark theme to your awesome script that would work across all the DI services? It would be another feather in your cap. An option to enable/disable that could also be added in the script settings page. Let me know if this is something that you can add.

Thanks!

**Comment by lethak** [comment]
Hi, may I suggest https://darkreader.org/

**Comment by Nzzyme** [comment]
Ok, thank you!
