### ISSUE TITLE
Volume ramp-up is not interruptible

### ISSUE THREAD

**Issue by Tremolo4** [lethak/digitally_imported_userscript#54]
Sometimes, the volume is (re-)set e.g. to 80% from 25% when I open di.fm. Not sure why (it was already happening before the recent update).

Thankfully, the userscript makes sure that the radio does not immediately blare at 80% when I press play thanks to the volume ramp-up feature. However, it is hopeless to try and adjust the volume before it has ramped up to 80% -- it just keeps going up. I have to take off my headphones quickly, wait until it has ramped up to 80%, turn it down, then put my headphones back on.

Idea for a fix: It would be nice if the ramp-up cancels once you start adjusting the volume.

**Comment by lethak** [comment]
Hi,
It will be in the next release,
thanks for the suggestion !

**Comment by Tremolo4** [comment]
Wow, thanks a lot! Looking forward to it.

And also thanks a lot for this script in general :)
