### ISSUE TITLE
Bug: Music downloaded with a randon filename 

### ISSUE THREAD

**Issue by Lightson73540** [lethak/digitally_imported_userscript#57]
1. Click download button

![opera_2022_03_08_14_36_terça-feira__9vEjpdusWi](https://user-images.githubusercontent.com/86080053/157294226-4d7540bf-ba3c-4309-bcb7-86f15efdccec.png)

2. Music opens in another tab

![opera_2022_03_08_14_37_terça-feira__eEw4DSVbMx](https://user-images.githubusercontent.com/86080053/157294395-e5940873-510f-4d70-86bd-4c4add0990c0.png)

3. Right click and select "save as"
4. Music is saved with randon numbers and letters in filename

![opera_2022_03_08_14_38_terça-feira__Am12AZgpjG](https://user-images.githubusercontent.com/86080053/157294470-07c650b5-4abb-413e-9875-82336f917408.png)

**Comment by lethak** [comment]
Hi,

Can you check this out https://github.com/lethak/LTKDIFMU-userscript/issues/36#issuecomment-703273642

I think this is the reason why.

I don't think I will be able to be of more help on the matter unless your script manager implements what is required to customize a download

What is your script manager by the way ?

I'll give another shot at trying to enhance that at some point
