### ISSUE TITLE
Script does not work on Firefox with default Tampermonkey installation

### ISSUE THREAD

**Issue by Tremolo4** [lethak/digitally_imported_userscript#60]
As discussed in chat, there seems to be a non-standard tampermonkey setting that is required for the script to work in firefox at the moment.

As a workaround, [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/) works.

**Comment by lethak** [comment]
Confirmed with FF 106.0 (64-bit) for windows
And Tempermonkey 4.18.0 (2022-09-30) for FF

**Comment by firx** [comment]
What's the non-standard tampermonkey setting required?

**Comment by Tremolo4** [comment]
> What's the non-standard tampermonkey setting required?

We don't know. :(
It stopped working for me on tampermonkey out of the blue. When I asked lethak, he eventually reset his tampermonkey settings to default, and then it stopped working for him too. We could not figure out a way to make it work again.

**Comment by lethak** [comment]
Sorry guys, no time to investigate at the moment

**Comment by Tremolo4** [comment]
Looks like they've fixed this issue in tampermonkey 4.18.1! At least for me on my current firefox profile.
