### ISSUE TITLE
Script need regional unblock support.

### ISSUE THREAD

**Issue by Quqas** [lethak/digitally_imported_userscript#61]
Now I see "We're sorry, but ad-supported DI.FM service is not available in your region."
It possible  fix with this script?

**Comment by lethak** [comment]
Are you a victim of some sort of Geofencing ? I think its serverside and could only be resolved with a VPN and new account using this VPN. Let me know how that turns out

**Comment by Quqas** [comment]
use hola vpn(extension) in chrome, ​but this not right way

seems like after page generate, traffic goes to true ip

I hope if script to force generate "player" page instead of "restricted" - it's may work

**Comment by lethak** [comment]
You should try with Brave browser in private (TOR) mode or a true non-browser VPN. The script won't help you much as the backend is the one sending you the audio, not just the page and player. Good luck to you
