### ISSUE TITLE
Numeric volume input not work on first load, until page refresh (F5)

### ISSUE THREAD

**Issue by Quqas** [lethak/digitally_imported_userscript#62]
chrome, tampermonkey, DIUserscript 2022.10.47

Load di.fm in New Incognito Window (tampermonkey enable) -> start playing = no Numeric volume input present.

After page reload and start play again = work fine 
![Безымянный](https://user-images.githubusercontent.com/38732439/205451144-30c053dc-325d-48d2-a976-f29622b47aa8.png)

**Comment by lethak** [comment]
Hi,
I am not reproducing atm. is it working when logged in ?
What OS and version of chrome and tempermonkey ?

**Comment by Quqas** [comment]
no Numeric volume input present if not logged in (when logging in, the page is refresh automatically )

win7 x64
chrome  97.0.4692.99
Tampermonkey 4.18.1

**Comment by Quqas** [comment]
I tested it in 2023.3.54 and now worked fine.

issue fixed
