### ISSUE TITLE
Does not Install

### ISSUE THREAD

**Issue by Nzzyme** [lethak/digitally_imported_userscript#67]
I have been trying to install the script on the latest version of Tampermonkey but I am unable to. The page always gets stuck while trying to install the script

![image](https://user-images.githubusercontent.com/6959116/232279171-ecb6625d-3b0c-4881-a19f-c712683b097c.png)

Can you please check?

**Comment by lethak** [comment]
I have noticed too, just give it some time it should work.

**Comment by Nzzyme** [comment]
Thanks. After waiting for a minute or so, I was able to install it.
