### ISSUE TITLE
[Non-DI] Page Elements Not Displayed Correctly following their switch to ajax player like DI

### ISSUE THREAD

**Issue by Nzzyme** [lethak/digitally_imported_userscript#68]
Hi, I installed your script and observed that some elements do not display correctly (only checked on radiotunes). See screenshot below:

![image](https://user-images.githubusercontent.com/6959116/232513526-7f2284c9-4b8b-4c73-a99a-ef342034839d.png)

Elements like skip, volume bar, loop track, download, etc. do not display correctly. Can you please check and fix?

**Comment by lethak** [comment]
Actually this is a big deal, they just adopted the DI player on non DI sites. 
I will have to adapt the script

**Comment by Nzzyme** [comment]
Thanks for fixing!
