### ISSUE TITLE
Global media controls bugs

### ISSUE THREAD

**Issue by Quqas** [lethak/digitally_imported_userscript#69]
Hi

I can not understand why the nextTrack button on the keyboard does not always work  (DI.fm)

Sometimes it works right away
sometimes need to refresh the page (one or more times)
and sometimes need to close / open chrome (also not the fact that it will help the first time)

No other media players are currently open.

Maybe there is a clear algorithm of actions in the browser to find out the reason? (logs, etc.)

Win7x64, Chrome, DIUserscript for AudioAddict platforms | 2023.4.92

**Comment by lethak** [comment]
Hi, make sure to upgrade Tampermonkey to at least version 4.19.0 and try again to be sure.
Not seing any problem on my side for the moment, have you tried with the chrome global controls from within the browser ?

this one

![68747470733a2f2f692e696d6775722e636f6d2f5347336c596b502e706e67](https://github.com/lethak/LTKDIFMU-userscript/assets/1705300/0c214691-aeff-48c7-8bc9-03988bfdc72d)

**Comment by Quqas** [comment]
- Tampermonkey 4.19.0 

-  Now i see problem {yes i first time use this widget ;)  },  "chrome global controls" has only play\pause button when bug, and i can't understand why.

Yes this not script-side problem... But maybe any ideas?

**Comment by lethak** [comment]
Looks like the script is not enabled or the feature itself in the settings menu, but having to reload seems to indicate its the good old injection order problem.

**Comment by Quqas** [comment]
i think found true reason - in "deep" stupid cache  

in incognito mode - work fine 10 from 10 times
in normal mode : 2-3 from 10....
many times pressed "clear site data" ( F12\application\storage ) but not affect

wtf? how to clear site(javascript) cache properly? i can't (wan't)full clear all chrome account data.

p.s. of course it's not script-side problem - but in site javascript... (i think)

**Comment by Quqas** [comment]
Thanks for the replies and your script.
You can close the issue.
I don’t understand what is wrong with this bad Chrome and what exactly helped - but for the last two days it has started to work normally, not only in incognito mode, but also in normal mode.
