### ISSUE TITLE
Track Details Hidden

### ISSUE THREAD

**Issue by Nzzyme** [lethak/digitally_imported_userscript#70]
@lethak : I enabled your script and opened zenradio.com and then logged in to the site, Later, I clicked on any one locked channel to open the channel page. I then clicked on the play button on the channel page. The track starts playing and I am able to see all the track details (track name, album, etc.) on the player at the bottom. However, I am unable to see the track details on the page besides the play button. See below screenshots:

**Without the script:**

![image](https://github.com/lethak/LTKDIFMU-userscript/assets/6959116/3f9d0cb7-8270-4ad5-83b6-c39972a0065e)

**With the script enabled:**

![image](https://github.com/lethak/LTKDIFMU-userscript/assets/6959116/ad53379e-11de-4a30-9203-aea8f5a583e0)

Was it removed on purpose as it is also available at the bottom of the page? This is also observed on radiotunes.com. Can you bring it back if possible?

**Comment by lethak** [comment]
From memory it was done on purpose as it was not being consistent with the bottom player and the unlock feature. It was displaying incorrect UI states and Track data.

Can you describe why you think it should be displayed anyway ? is it related to premium account ? or just "bing blank hole in the page is ugly" ?

I'll look into making it disappear only for non premium users

**Comment by Nzzyme** [comment]
> 

Thanks for your response. That's fine if it was intentionally removed. As we are also able to view the track details at the bottom player. You may close this
