### ISSUE TITLE
[Greasemonkey] Script not working with Firefox 57 "Quantum"

### ISSUE THREAD

**Issue by padraigdoran** [lethak/digitally_imported_userscript#8]
This script has stopped working on di.fm

// @version     2017.10.0

Console log filtered by "DIUserscript":

`
[DIUserscript] Initializing
Digitally%20Imported%20Userscript:379:5

[DIUserscript] window.document ready
Digitally%20Imported%20Userscript:503:9

[DIUserscript] redefineCommands
Digitally%20Imported%20Userscript:419:9

[DIUserscript] Initializing
Digitally%20Imported%20Userscript:379:5
`

**Comment by padraigdoran** [comment]
Full log:

[DIUserscript] Initializing
Digitally%20Imported%20Userscript:379:5
                                
application-69b8b117aab5ede45f928160f562956d.js:79:16677
????????????????????????????????
application-69b8b117aab5ede45f928160f562956d.js:79:16677
? Internet Radio Platform 1.20 ?
application-69b8b117aab5ede45f928160f562956d.js:79:16677
?------------------------------?
application-69b8b117aab5ede45f928160f562956d.js:79:16677
?      © AudioAddict Inc       ?
application-69b8b117aab5ede45f928160f562956d.js:79:16677
?     All Rights Reserved      ?
application-69b8b117aab5ede45f928160f562956d.js:79:16677
????????????????????????????????
application-69b8b117aab5ede45f928160f562956d.js:79:16677
                                
application-69b8b117aab5ede45f928160f562956d.js:79:16677
[12:41:12.587] di.ui.Events: initiated.
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:12.592] AudioAddict.Modules.Social: Initializing...
application-69b8b117aab5ede45f928160f562956d.js:79:16677
[12:41:12.594] AudioAddict.Modules.Social: Initialized.
application-69b8b117aab5ede45f928160f562956d.js:79:16677
[12:41:12.604] AudioAddict.social.Auth: Initialized with params:  
Object { userLoggedIn: true, defaultButtonSize: 25, gigyaLoginParams: {…} }
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:12.750] di.App: version: 841455c403c6293e8b5cf5705077651096f30bf5
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:12.751] di.App: deployed: 2017-11-15 22:19:57 +0000
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:12.986] di.module.TimedAlerts: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.27] di.application.module.Autoloader: START module: {BannersApp} with args 
Array [ {…} ]
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.44] di.application.module.Autoloader: START module: {ChannelBrowserApp} with args 
Array [ {…} ]
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.78] di.application.module.Autoloader: START module: {UpcomingShowsApp} with args 
Array [ {…} ]
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.79] di.tracking.adwords: Remarketing 
application-69b8b117aab5ede45f928160f562956d.js:79:15909
Loading failed for the <script> with source “https://www.googleadservices.com/pagead/conversion_async.js”.
www.di.fm:9
[12:41:13.226] di.collection.AdRulesets: Parsing server response; filtering by country
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.253] di.model.TimedAlert[2/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.256] di.model.TimedAlert[4/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.257] di.model.TimedAlert[5/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.258] di.model.TimedAlert[6/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.260] di.model.TimedAlert[7/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.262] di.model.TimedAlert[8/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.264] di.model.TimedAlert[9/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.266] di.model.TimedAlert[10/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.269] di.model.TimedAlert[11/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.271] di.model.TimedAlert[108/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.273] di.model.TimedAlert[109/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.275] di.model.TimedAlert[110/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.276] di.model.TimedAlert[168/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.277] di.model.TimedAlert[111/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.278] di.model.TimedAlert[112/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.278] di.model.TimedAlert[113/custom/audio_playback]: started
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.295] WebplayerApp.Ads.Supervisor: midroll interval complete
application-69b8b117aab5ede45f928160f562956d.js:79:15909
error={ReferenceError: Stripe is not defined}, url={https://www.di.fm/}, line={91}
application-69b8b117aab5ede45f928160f562956d.js:79:22533
[DIUserscript] window.document ready
Digitally%20Imported%20Userscript:503:9
[DIUserscript] redefineCommands
Digitally%20Imported%20Userscript:419:9
[12:41:13.312] AudioAddict.social.Auth: Previously initialized, returning existing instance
application-69b8b117aab5ede45f928160f562956d.js:79:15909
[12:41:13.313] AudioAddict.social.Auth: Updated params: 
Object { userLoggedIn: true, defaultButtonSize: 25, gigyaLoginParams: {…} }
application-69b8b117aab5ede45f928160f562956d.js:79:15909
Loading failed for the <script> with source “https://connect.facebook.net/en_US/fbevents.js”.
www.di.fm:1
Loading failed for the <script> with source “https://bat.bing.com/bat.js”.
www.di.fm:1
The resource at “https://connect.facebook.net/en_US/sdk.js” was blocked because tracking protection is enabled.
[Learn More]
www.di.fm
Loading failed for the <script> with source “https://connect.facebook.net/en_US/sdk.js”.
www.di.fm:1
Loading failed for the <script> with source “https://js.stripe.com/v2”.
www.di.fm:90
ReferenceError: Stripe is not defined
[Learn More]
www.di.fm:91:3
[DIUserscript] Initializing
Digitally%20Imported%20Userscript:379:5
Loading failed for the <script> with source “https://s.adroll.com/j/roundtrip.js?_=1511268072572”.
www.di.fm:1
Source map error: request failed with status 404
Resource URL: https://cdn.audioaddict.com/di.fm/assets/application-69b8b117aab5ede45f928160f562956d.js
Source Map URL: /assets/maps/application-722e768649ddd4cdcb353a7c8d1bb2c4.map
[Learn More]
Loading failed for the <script> with source “https://beacon.errorception.com/5988cdd3d800d3e4490003a9.js”.
www.di.fm:1
[12:41:16.255] di.analytics: trackEvent: category: Ad Blocker, action: Detected, nonInteractive: 1
application-69b8b117aab5ede45f928160f562956d.js:79:15909
Loading failed for the <script> with source “https://gscounters.us1.gigya.com/gscounters.sendReport?reports=%5B%7B%22name%22%3A%22loadc%22%2C%22time%22%3A%221511268072472%22%2C%22reportData%22%3A%7B%22sref%22%3A%22%22%7D%7D%5D&APIKey=3_vTH3_xeWJBW3D1Lo6tafubj3l30Gt7NbRBgBRgF5l_P5cdQUwXwiwvkbqqM90Bu3&sdk=js_7.4.30&pageURL=https%3A%2F%2Fwww.di.fm%2F&format=jsonp&callback=gigya.callback&context=R3780080713”.
Api.aspx:1
Source map error: request failed with status 404
Resource URL: https://cdn.audioaddict.com/di.fm/assets/modernizr-f9bdf8436fb6dd1c003b7d8d4416ce40.js
Source Map URL: /assets/maps/modernizr-68794dff385db6e9a53868455b47c243.map
[Learn More]
Source map error: request failed with status 404
Resource URL: https://cdn.audioaddict.com/di.fm/assets/blockadblock-93fc3395f09326b8a934f369fde11e9e.js
Source Map URL: /assets/maps/blockadblock-7d84580c17674c3579ce79267b17264d.map
[Learn More]

**Comment by lethak** [comment]
I, thanks for your report, I will look into it asap

**Comment by lethak** [comment]
Are you using the lastest version of greasemonkey or tampermonkey ?

**Comment by padraigdoran** [comment]
Greasemonkey 4.0
Firefox "Quantum" 57.0

Everything the latest version.

**Comment by lethak** [comment]
Indeed.

It seems GM decided to break BC because of the new Firefox 57

More documentation: 
* [Greasemonkey 4 For Users] (https://www.greasespot.net/2017/09/greasemonkey-4-for-users.html)
* [Greasemonkey 4 For Script Authors ](https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html)

Since I don't want/have time to support specific configuration for each userscript extension, I will simply advise to drop Greasemonkey and use [Tampermonkey for Firefox](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/) instead; It seems to run well on my end.
